import { VideoProject } from "@/types/videos";

export const allVideoProjects: VideoProject[] = [
  {
    id: "F-1DqS0iQ0s",
    video_title: "Facade Process",
    video_description: `Discover how modern building facades are engineered and installed with precision, transforming architectural concepts into high-performance exteriors.`,
    tags: ["Modern building facades", "Facade Installation"],
    cover_image: "F-1DqS0iQ0s",
    publish_date: "2026-04-16",
    client_name: "HG Walls",
    client_image: "/companies/HG-Walls.jpg",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/F-1DqS0iQ0s?si=z2ofxSuaN7VKCJsI",
    project_images: [],
    category: ["AiShorts", "Architecture"],
    duration: "0:16",
    software_used: ["Adobe Premiere Pro"],
  },
  {
    id: "CoL99xlmBHg",
    video_title: "ACP Transformation",
    video_description:
      "Apply logic to simplify your conditional problems. Watch the video to understand how!",
    tags: ["ACP", "Conditional Logic", "Problem Solving", "Shorts"],
    cover_image: "CoL99xlmBHg",
    publish_date: "2026-05-19",
    client_name: "HG Walls",
    client_image: "/companies/HG-Walls.jpg",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/CoL99xlmBHg?si=pVG6T98Sr0JpBgZX",
    project_images: [],
    category: ["AiShorts", "Architecture"],
    duration: "0:17",
    software_used: ["Adobe Premiere Pro"],
  },
  {
    id: "oKp6CHbP2sE",
    video_title: "Premium pergola solutions that transform terraces, rooftops, resorts,villas",
    video_description:
      "Premium pergola solutions by HG Walls, crafted to elevate terraces, villas, cafés, resorts, and commercial spaces with modern design.",
    tags: ["Premium pergola", "terraces", "rooftops", "resorts"],
    cover_image: "oKp6CHbP2sE",
    publish_date: "2026-06-13",
    client_name: "HG Walls",
    client_image: "/companies/HG-Walls.jpg",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/oKp6CHbP2sE?si=vViXGGooXSWHln6r",
    project_images: [],
    category: ["AiShorts", "Architecture"],
    duration: "0:22",
    software_used: ["Adobe Premiere Pro"],
  },
  {
    id: "0wGDE0a5Dyw",
    video_title: " Complete Facade Installation Process | From Design to Installation",
    video_description:
      "A complete overview of HG Walls' facade installation process, showcasing precision engineering, quality craftsmanship, and modern exterior solutions.",
    tags: ["Facade Installation", "Structural Glazing", "Project Showcase", "Architecture"],
    cover_image: "0wGDE0a5Dyw",
    publish_date: "2026-06-29",
    client_name: "HG Walls",
    client_image: "/companies/HG-Walls.jpg",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/0wGDE0a5Dyw?si=V6kRbkJWMJrUHOiU",
    project_images: [],
    category: ["AiShorts", "Architecture"],
    duration: "0:18",
    software_used: ["Adobe Premiere Pro"],
  },
  {
    id: "-kkknSOdgwo",
    video_title: "पुण्य के नाम पर पाप? | आस्था के नाम पर प्रदूषण",
    video_description:
      "यह वीडियो बताता है कि सच्ची आस्था प्रकृति की रक्षा में है, न कि नदियों को प्रदूषित करने वाली परंपराओं में।",
    tags: ["सामाजिक जागरूकता", "पर्यावरण जागरूकता", "धार्मिक जागरूकता", "शैक्षणिक शॉर्ट्स"],
    cover_image: "-kkknSOdgwo",
    publish_date: "2026-03-26",
    client_name: "Ghoomantu Experiences",
    client_image: "/companies/ghoomantu-experience.jpg",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/-kkknSOdgwo?si=l8HCRjkNf942lEye",
    project_images: [],
    category: ["Shorts"],
    duration: "0:41",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "OaN7iV8zvUY",
    video_title: "शिक्षित होना, धार्मिक होने से ज़्यादा ज़रूरी है",
    video_description:
      "यह वीडियो होली के दौरान सम्मान, जिम्मेदारी और सामाजिक जागरूकता का संदेश देता है, बताते हुए कि परंपरा कभी भी बदसलूकी का समर्थन नहीं करती।",
    tags: ["सामाजिक जागरूकता", "शैक्षणिक शॉर्ट्स", "त्योहार जागरूकता", "जन-जागरूकता"],
    cover_image: "OaN7iV8zvUY",
    publish_date: "2026-03-31",
    client_name: "Ghoomantu Experiences",
    client_image: "/companies/ghoomantu-experience.jpg",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/OaN7iV8zvUY?si=q9GE0PpnUQoHpwgw",
    project_images: [],
    category: ["Shorts"],
    duration: "0:33",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "cSNlAjq5mv4",
    video_title: "Travel with purpose",
    video_description:
      "Ghoomantu is a travel community that promotes sustainable travel, offbeat destinations, and authentic group adventures across India.",
    tags: ["Educational Shorts",
      "Travel Guide",
      "Social Awareness",
      "Storyteling"],
    cover_image: "cSNlAjq5mv4",
    publish_date: "2026-03-07",
    client_name: "Ghoomantu Experiences",
    client_image: "/companies/ghoomantu-experience.jpg",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/cSNlAjq5mv4?si=V56JDTgGC6FBeKM6",
    project_images: [],
    category: ["Shorts"],
    duration: "1:49",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "XM0DTazadzc",
    video_title: "पहाड़ों में पार्टी और SHOR SHARABA? 🤬 | बंद करो ये तमाशा",
    video_description: "यह वीडियो सम्मानजनक और जिम्मेदार यात्रा के महत्व को उजागर करता है, साथ ही यात्रियों को प्रकृति और स्थानीय संस्कृति का सम्मान करने के लिए प्रेरित करता है।",
    tags: [
      "Educational Shorts",
      "Travel Guide",
      "Social Awareness",
      "Storyteling",
    ],
    cover_image: "XM0DTazadzc",
    publish_date: "2026-04-01",
    client_name: "Ghoomantu Experiences",
    client_image: "/companies/ghoomantu-experience.jpg",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/XM0DTazadzc?si=c3JWXdMV0OW6qqyq",
    project_images: [],
    category: ["Shorts"],
    duration: "0:58",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "-UqbDmhtqM0",
    video_title:
      "Traveller Bano, Tourist Nahi | Don't Come to Mountains for Comfort",
    video_description: `Mountains are meant to be experienced, not exploited. Responsible travel is about respecting nature, supporting local communities, and preserving the Himalayas.`,
    tags: ["Educational Shorts", "Travel Guide", "Social Awareness", "Storyteling"],
    cover_image: "-UqbDmhtqM0",
    publish_date: "2026-03-25",
    client_name: "Ghoomantu Experiences",
    client_image: "/companies/ghoomantu-experience.jpg",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/-UqbDmhtqM0?si=nhkBcAkMOiydyrUR",
    project_images: [],
    category: ["Shorts"],
    duration: "0:44",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "PN7WwBWRsq8",
    video_title: "आस्था या अंधविश्वास? प्रकृति को नुकसान पहुँचाना धर्म नहीं",
    video_description:
      "गंगा और अन्य नदियों में दूध, घी या पूजा सामग्री डालने से जल प्रदूषण बढ़ता है और जलीय जीवों के लिए ऑक्सीजन की कमी पैदा हो सकती है।",
    tags: ["Environment", "Sustainability", "Green Revolution", "Storyteling"],
    cover_image: "PN7WwBWRsq8",
    publish_date: "2026-03-28",
    client_name: "Ghoomantu Experiences",
    client_image: "/companies/ghoomantu-experience.jpg",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/PN7WwBWRsq8?si=IoAqrgb8M3-wNgbv",
    project_images: [],
    category: ["Shorts","Motion Graphics"],
    duration: "1:05",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "DXcFgBUiKW3",
    video_title: "Obesity Isn’t a Disease… Then What Is It?",
    video_description:
      "Most people treat obesity as just a body issue… but what if it's actually a system disorder? It's not just about fat — it's about mind, metabolism & energy imbalance. You don't fix it by starving, you fix it by understanding your system. That's where PHZ works differently: mind alignment, energy balance, and body regulation. Because real transformation doesn't start from the body — it starts from the system.",
    tags: ["Obesity", "Health Awareness", "Wellness", "Reels"],
    cover_image: "/project-images/phz-obesity-cover.jpg",
    publish_date: "2026-04-22",
    client_name: "Positive Health Zone",
    client_image: "/companies/positive-health-zone.jpg",
    client_feedback: "",
    video_link: "https://www.instagram.com/reel/DXcFgBUiKW3/",
    project_images: [],
    category: ["Shorts"],
    software_used: ["Adobe Premiere Pro"],
    platform: "instagram",
    local_video: "/project-images/phz-obesity-reel.mp4",
  },
  {
    id: "-iqghJvuGgk",
    video_title: "The Man Who Destroyed Michael Jackson",
    video_description: `Michael Jackson became the King of Pop—but behind the fame was a childhood shaped by fear, abuse, and his father's relentless pressure.`,
    tags: ["Michael Jackson Documentary", "Documentary Editing", "Storytelling"],
    cover_image: "-iqghJvuGgk",
    publish_date: "2026-05-18",
    client_name: "The Public Decoder",
    client_image: "/companies/raza-profile.jpg",
    client_feedback: "",
    video_link: "https://youtu.be/-iqghJvuGgk?si=8E4PZ5DZ6999Pt42",
    project_images: [],
    category: ["Documentary"],
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
];
